export const SUPABASE_URL='https://cyhjzyoezhdlqybgaldk.supabase.co'
export const SUPABASE_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYW5vbiIsImlhdCI6MTYyMTkyMjMyMSwiZXhwIjoxOTM3NDk4MzIxfQ.haVNnBl8b-52vLVHTK4vjdOIhH8LHjGUwM8wz7SKsJg'
export const QUOTE_API_KEY = 'vZCw4L/8gSfm9bLEvePjkg==kbIB78nd8gCtfrvL';